platform :ios, '10.0'
use_frameworks!

target 'ACDataSyncing_Example' do
  pod 'ACDataSyncing', :path => '../'

  target 'ACDataSyncing_Tests' do
    inherit! :search_paths

    pod 'Quick'
  pod 'Nimble'
  end
end
